export const projectsObjA = {
    id:'projects-section-data',
    title:'My Projects Of Interest',
    cardContentTitle:'Antelope Classifier',
    cardContentBody:'After training a machine learning model you need to deploy it to show potential stakeholders what the results would look like With a decent UI, not jupyter notebook sto achieve any sort of buyback from the people/business that potentially want and can pay for this type of service.',
    cardActionsText:'Read More',
    cardContentTitleA:'Personal Website',
    cardContentBodyA:'',
    cardActionsTextA:'Read More',
    cardContentTitleB:'Zigoti Coffee Website',
    cardContentBodyB:'',
    cardActionsTextB:'Read More',
    img:'https://d322abd807wvow.cloudfront.net/rubanza-silver/IMG_8803.JPG',
    alt:'Antelope Classfier Project',
    imgA:'https://d322abd807wvow.cloudfront.net/rubanza-silver/IMG_8803.JPG',
    altA:'Antelope Classfier Project',
    imgB:'https://d322abd807wvow.cloudfront.net/rubanza-silver/IMG_8803.JPG',
    altB:'Antelope Classfier Project',
};
